# Generated by Django 5.1.1 on 2025-02-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sneaker_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='size',
        ),
    ]
