# Generated by Django 5.1.1 on 2025-02-23 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sneaker_description_sneaker_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='description',
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(upload_to='sneakers/'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sneaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sneaker')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='accounts.sneaker')),
            ],
        ),
        migrations.DeleteModel(
            name='SneakerFavorite',
        ),
    ]
