# Generated by Django 5.1.1 on 2025-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_sneaker_description_alter_sneaker_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='sneakers/'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
