# Generated by Django 5.1.1 on 2025-02-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_sneaker_image_alter_sneaker_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='image',
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='SneakerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.sneaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sneaker')},
            },
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
