# Generated by Django 5.1.1 on 2025-02-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_favorites_remove_sneaker_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='price',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sneakers/'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='size',
            field=models.DecimalField(decimal_places=2, default=42, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
