# Generated by Django 5.1.1 on 2025-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_sneaker_price_sneaker_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
