# Generated by Django 5.1.1 on 2025-02-24 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sneaker_price_alter_sneaker_image_sneakercart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sneakercart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='price',
        ),
        migrations.AlterField(
            model_name='sneakercart',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sneaker'),
        ),
        migrations.AlterField(
            model_name='sneakercart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='sneakercart',
            name='size',
        ),
    ]
