# Generated by Django 5.1.1 on 2025-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_sneakercart_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
